### ISSUE TITLE
[Task] <Device API>

### ISSUE THREAD

**Issue by Cxrdary** [Cxrdary/RGBLightController#10]
### Description of work

Find an API to interact with the light strips with.

**Comment by Cxrdary** [comment]
Decided on diozero library to interface with lightstrips.

**Comment by MichaelAndrew22** [comment]
PI4J seems simpler on further inspection, to me at least.

**Comment by Cxrdary** [comment]
after looking at that example you shared I'll have to agree

**Comment by MichaelAndrew22** [comment]
Awesome, well I guess we should adapt and go with that one right?
Lets get it linked into our project and then we should be off to the races.

**Comment by MichaelAndrew22** [comment]
We can import Pi4J with maven like in the JavaFX dependencies video for Week 3.
